package com.wassabi.model;
// Generated 19 de nov. de 2022 11:01:21 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "Categoria")
public class Categoria implements java.io.Serializable {

	private Integer categoriaId;
	private String categoriaNome;
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Categoria() {
	}

	public Categoria(String categoriaNome) {
		this.categoriaNome = categoriaNome;
	}

	public Categoria(String categoriaNome, Set<Produto> produtos) {
		this.categoriaNome = categoriaNome;
		this.produtos = produtos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "categoria_id", unique = true, nullable = false)
	public Integer getCategoriaId() {
		return this.categoriaId;
	}

	public void setCategoriaId(Integer categoriaId) {
		this.categoriaId = categoriaId;
	}

	@Column(name = "categoria_nome", nullable = false, length = 30)
	public String getCategoriaNome() {
		return this.categoriaNome;
	}

	public void setCategoriaNome(String categoriaNome) {
		this.categoriaNome = categoriaNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
