package com.wassabi.model;
// Generated 19 de nov. de 2022 11:01:21 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "Cliente", uniqueConstraints = @UniqueConstraint(columnNames = "cliente_cpf"))
public class Cliente implements java.io.Serializable {

	private Integer clienteId;
	private String clienteNome;
	private String clienteCpf;
	private String clienteEndereco;
	private String clienteCartao;
	private String clienteTelefone;
	private Set<Venda> vendas = new HashSet<Venda>(0);

	public Cliente() {
	}

	public Cliente(String clienteNome, String clienteCpf, String clienteEndereco, String clienteCartao,
			String clienteTelefone) {
		this.clienteNome = clienteNome;
		this.clienteCpf = clienteCpf;
		this.clienteEndereco = clienteEndereco;
		this.clienteCartao = clienteCartao;
		this.clienteTelefone = clienteTelefone;
	}

	public Cliente(String clienteNome, String clienteCpf, String clienteEndereco, String clienteCartao,
			String clienteTelefone, Set<Venda> vendas) {
		this.clienteNome = clienteNome;
		this.clienteCpf = clienteCpf;
		this.clienteEndereco = clienteEndereco;
		this.clienteCartao = clienteCartao;
		this.clienteTelefone = clienteTelefone;
		this.vendas = vendas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cliente_id", unique = true, nullable = false)
	public Integer getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(Integer clienteId) {
		this.clienteId = clienteId;
	}

	@Column(name = "cliente_nome", nullable = false, length = 80)
	public String getClienteNome() {
		return this.clienteNome;
	}

	public void setClienteNome(String clienteNome) {
		this.clienteNome = clienteNome;
	}

	@Column(name = "cliente_cpf", unique = true, nullable = false, length = 14)
	public String getClienteCpf() {
		return this.clienteCpf;
	}

	public void setClienteCpf(String clienteCpf) {
		this.clienteCpf = clienteCpf;
	}

	@Column(name = "cliente_endereco", nullable = false, length = 80)
	public String getClienteEndereco() {
		return this.clienteEndereco;
	}

	public void setClienteEndereco(String clienteEndereco) {
		this.clienteEndereco = clienteEndereco;
	}

	@Column(name = "cliente_cartao", nullable = false, length = 100)
	public String getClienteCartao() {
		return this.clienteCartao;
	}

	public void setClienteCartao(String clienteCartao) {
		this.clienteCartao = clienteCartao;
	}

	@Column(name = "cliente_telefone", nullable = false, length = 20)
	public String getClienteTelefone() {
		return this.clienteTelefone;
	}

	public void setClienteTelefone(String clienteTelefone) {
		this.clienteTelefone = clienteTelefone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Venda> getVendas() {
		return this.vendas;
	}

	public void setVendas(Set<Venda> vendas) {
		this.vendas = vendas;
	}

        /** 
     * @return String
     */
    @Override
    public String toString() {
        return "Cliente [clienteId=" + clienteId + ", clienteNome=" + clienteNome + ", clienteCpf=" + clienteCpf + ", cliente_endereco" + clienteEndereco +", clienteTelefone=" + clienteTelefone + "]";
    }

}
