package com.wassabi.model;
// Generated 19 de nov. de 2022 11:01:21 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendaHasProdutoId generated by hbm2java
 */
@Embeddable
public class VendaHasProdutoId implements java.io.Serializable {

	private int vendaId;
	private int produtoId;

	public VendaHasProdutoId() {
	}

	public VendaHasProdutoId(int vendaId, int produtoId) {
		this.vendaId = vendaId;
		this.produtoId = produtoId;
	}

	@Column(name = "venda_id", nullable = false)
	public int getVendaId() {
		return this.vendaId;
	}

	public void setVendaId(int vendaId) {
		this.vendaId = vendaId;
	}

	@Column(name = "produto_id", nullable = false)
	public int getProdutoId() {
		return this.produtoId;
	}

	public void setProdutoId(int produtoId) {
		this.produtoId = produtoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VendaHasProdutoId))
			return false;
		VendaHasProdutoId castOther = (VendaHasProdutoId) other;

		return (this.getVendaId() == castOther.getVendaId()) && (this.getProdutoId() == castOther.getProdutoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVendaId();
		result = 37 * result + this.getProdutoId();
		return result;
	}

    /** 
     * @return String
     */
    @Override
    public String toString() {
        return "VendaHasProdutoId [vendaId=" + vendaId + ", produtoId=" + produtoId + "]";
    }

}
