package com.wassabi.model;
// Generated 18 de nov. de 2022 00:13:14 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendaHasProdutoId generated by hbm2java
 */
@Embeddable
public class VendaHasProdutoId implements java.io.Serializable {

	private int vendaId;
	private int produtoId;
	private int quantidade;

	public VendaHasProdutoId() {
	}

	public VendaHasProdutoId(int vendaId, int produtoId, int quantidade) {
		this.vendaId = vendaId;
		this.produtoId = produtoId;
		this.quantidade = quantidade;
	}

	@Column(name = "venda_id", nullable = false)
	public int getVendaId() {
		return this.vendaId;
	}

	public void setVendaId(int vendaId) {
		this.vendaId = vendaId;
	}

	@Column(name = "produto_id", nullable = false)
	public int getProdutoId() {
		return this.produtoId;
	}

	public void setProdutoId(int produtoId) {
		this.produtoId = produtoId;
	}

	@Column(name = "quantidade", nullable = false)
	public int getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VendaHasProdutoId))
			return false;
		VendaHasProdutoId castOther = (VendaHasProdutoId) other;

		return (this.getVendaId() == castOther.getVendaId()) && (this.getProdutoId() == castOther.getProdutoId())
				&& (this.getQuantidade() == castOther.getQuantidade());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVendaId();
		result = 37 * result + this.getProdutoId();
		result = 37 * result + this.getQuantidade();
		return result;
	}

}
